env-variables:
  - project_root: ./
  - openai_api_key: 
  - elastic_url: 
  - elastic_password: 
  - ca_cert: ./http_ca.crt

data: 
  unprocessed-files: ./data/
  processed-files: ./data/processed_files

preprocess:
  chunk-size: 1000
  overlap: 100

embedding:
  dimension: 200
  openai-model: text-embedding-3-small


test_control_variable:
  do_not_delete: 
